/* Kataloge: LaTeX-Befehle, Umgebungen, Symbole, Snippets */

/* ------------------------------------------------------------ Befehle */
/* apply: Snippet-Syntax mit ${} und $0 (Cursor) */

export const COMMANDS = [
  // Structure
  { label: '\\documentclass', detail: 'Document class', apply: '\\documentclass[${1:12pt}]{${2:article}}', section: 'Structure' },
  { label: '\\usepackage', detail: 'Load package', apply: '\\usepackage[${1:}]{${2}}', section: 'Structure' },
  { label: '\\begin', detail: 'Begin environment', apply: '\\begin{${1:equation}}\n\t$0\n\\end{$1}', section: 'Structure' },
  { label: '\\end', detail: 'End environment', apply: '\\end{${1:equation}}', section: 'Structure' },
  { label: '\\title', detail: 'Set title', apply: '\\title{${1}}', section: 'Structure' },
  { label: '\\author', detail: 'Set author', apply: '\\author{${1}}', section: 'Structure' },
  { label: '\\date', detail: 'Set date', apply: '\\date{${1:\\today}}', section: 'Structure' },
  { label: '\\maketitle', detail: 'Create title page', apply: '\\maketitle', section: 'Structure' },
  { label: '\\tableofcontents', detail: 'Table of contents', apply: '\\tableofcontents', section: 'Structure' },
  { label: '\\listoffigures', detail: 'List of figures', apply: '\\listoffigures', section: 'Structure' },
  { label: '\\listoftables', detail: 'List of tables', apply: '\\listoftables', section: 'Structure' },
  { label: '\\newpage', detail: 'Page break', apply: '\\newpage', section: 'Structure' },
  { label: '\\clearpage', detail: 'Clear page (including floats)', apply: '\\clearpage', section: 'Structure' },
  { label: '\\appendix', detail: 'Start appendix', apply: '\\appendix', section: 'Structure' },
  { label: '\\chapter', detail: 'Chapter', apply: '\\chapter{${1}}', section: 'Structure' },
  { label: '\\section', detail: 'Section', apply: '\\section{${1}}', section: 'Structure' },
  { label: '\\subsection', detail: 'Subsection', apply: '\\subsection{${1}}', section: 'Structure' },
  { label: '\\subsubsection', detail: 'Unter-Subsection', apply: '\\subsubsection{${1}}', section: 'Structure' },
  { label: '\\paragraph', detail: 'Paragraph with heading', apply: '\\paragraph{${1}}', section: 'Structure' },
  { label: '\\label', detail: 'Set label', apply: '\\label{${1:sec:}}', section: 'Structure' },
  { label: '\\part', detail: 'Part (books)', apply: '\\part{${1}}', section: 'Structure' },

  // Formattingting
  { label: '\\textbf', detail: 'Bold', apply: '\\textbf{${1}}', section: 'Formatting' },
  { label: '\\textit', detail: 'Italic', apply: '\\textit{${1}}', section: 'Formatting' },
  { label: '\\emph', detail: 'Emphasis', apply: '\\emph{${1}}', section: 'Formatting' },
  { label: '\\underline', detail: 'Underlined', apply: '\\underline{${1}}', section: 'Formatting' },
  { label: '\\texttt', detail: 'Sans/Mono', apply: '\\texttt{${1}}', section: 'Formatting' },
  { label: '\\textsc', detail: 'Uppercase', apply: '\\textsc{${1}}', section: 'Formatting' },
  { label: '\\textsl', detail: 'Slanted text', apply: '\\textsl{${1}}', section: 'Formatting' },
  { label: '\\smallcaps', detail: 'Small caps', apply: '\\textsc{${1}}', section: 'Formatting' },
  { label: '\\textrm', detail: 'Serif type', apply: '\\textrm{${1}}', section: 'Formatting' },
  { label: '\\textsf', detail: 'Sans serif type', apply: '\\textsf{${1}}', section: 'Formatting' },
  { label: '\\textsuperscript', detail: 'Superscript', apply: '\\textsuperscript{${1}}', section: 'Formatting' },
  { label: '\\textsubscript', detail: 'Subscript', apply: '\\textsubscript{${1}}', section: 'Formatting' },
  { label: '\\footnotesize', detail: 'Footnote size', apply: '\\footnotesize', section: 'Formatting' },
  { label: '\\small', detail: 'Small text', apply: '\\small', section: 'Formatting' },
  { label: '\\large', detail: 'Large text', apply: '\\large', section: 'Formatting' },
  { label: '\\Large', detail: 'Larger', apply: '\\Large', section: 'Formatting' },
  { label: '\\huge', detail: 'Very large', apply: '\\huge', section: 'Formatting' },
  { label: '\\centering', detail: 'Center', apply: '\\centering', section: 'Formatting' },
  { label: '\\raggedright', detail: 'Left aligned', apply: '\\raggedright', section: 'Formatting' },
  { label: '\\footnote', detail: 'Footnote', apply: '\\footnote{${1}}', section: 'Formatting' },
  { label: '\\phantom', detail: 'Invisible placeholder', apply: '\\phantom{${1}}', section: 'Formatting' },
  { label: '\\verb', detail: 'Literal text (delimited by |)', apply: '\\verb|${1}|', section: 'Formatting' },

  // Lists
  { label: '\\item', detail: 'Listseintrag', apply: '\\item ${1}', section: 'Lists' },
  { label: '\\hline', detail: 'Horizontal table rule', apply: '\\hline', section: 'Lists' },
  { label: '\\cline', detail: 'Partial table rule', apply: '\\cline{${1:1-3}}', section: 'Lists' },

  // References
  { label: '\\ref', detail: 'Reference (number)', apply: '\\ref{${1}}', section: 'References' },
  { label: '\\eqref', detail: 'Equation reference', apply: '\\eqref{${1}}', section: 'References' },
  { label: '\\autoref', detail: 'Typed reference (cleveref)', apply: '\\autoref{${1}}', section: 'References' },
  { label: '\\cref', detail: 'cleveref reference', apply: '\\cref{${1}}', section: 'References' },
  { label: '\\Cref', detail: 'cleveref (Groß)', apply: '\\Cref{${1}}', section: 'References' },
  { label: '\\pageref', detail: 'Seitenverweis', apply: '\\pageref{${1}}', section: 'References' },
  { label: '\\cite', detail: 'Zitat', apply: '\\cite{${1}}', section: 'References' },
  { label: '\\citep', detail: 'Zitat (Klammer)', apply: '\\citep{${1}}', section: 'References' },
  { label: '\\citet', detail: 'Zitat mit Namen', apply: '\\citet{${1}}', section: 'References' },
  { label: '\\parencite', detail: 'biblatex-Klammerzitat', apply: '\\parencite{${1}}', section: 'References' },
  { label: '\\textcite', detail: 'biblatex-Textzitat', apply: '\\textcite{${1}}', section: 'References' },
  { label: '\\footcite', detail: 'biblatex-Footnotenzitat', apply: '\\footcite{${1}}', section: 'References' },
  { label: '\\citeauthor', detail: 'Autorennennung', apply: '\\citeauthor{${1}}', section: 'References' },
  { label: '\\citeyear', detail: 'Jahresnennung', apply: '\\citeyear{${1}}', section: 'References' },
  { label: '\\url', detail: 'URL', apply: '\\url{${1:https://}}', section: 'References' },
  { label: '\\href', detail: 'Hyperlink', apply: '\\href{${1:https://}}{${2:Text}}', section: 'References' },
  { label: '\\bibliography', detail: 'Bib-files laden', apply: '\\bibliography{${1:references}}', section: 'References' },
  { label: '\\bibliographystyle', detail: 'Literaturstil', apply: '\\bibliographystyle{${1:plain}}', section: 'References' },
  { label: '\\printbibliography', detail: 'biblatex-Literaturverzeichnis', apply: '\\printbibliography', section: 'References' },
  { label: '\\addbibresource', detail: 'biblatex-Ressource', apply: '\\addbibresource{${1:references.bib}}', section: 'References' },

  // Graphics & Tabellen
  { label: '\\includegraphics', detail: 'Graphics einfügen', apply: '\\includegraphics[width=${1:0.8\\linewidth}]{${2}}', section: 'Graphics' },
  { label: '\\graphicspath', detail: 'Graphicspfade', apply: '\\graphicspath{{${1:images/}}}', section: 'Graphics' },
  { label: '\\caption', detail: 'Bild-/Tabellenunterschrift', apply: '\\caption{${1}}', section: 'Graphics' },
  { label: '\\centering', detail: 'Center', apply: '\\centering', section: 'Graphics' },
  { label: '\\toprule', detail: 'booktabs Oberlinie', apply: '\\toprule', section: 'Graphics' },
  { label: '\\midrule', detail: 'booktabs Mittellinie', apply: '\\midrule', section: 'Graphics' },
  { label: '\\bottomrule', detail: 'booktabs Unterlinie', apply: '\\bottomrule', section: 'Graphics' },
  { label: '\\multicolumn', detail: 'Spaltenübergreifend', apply: '\\multicolumn{${1:2}}{${2:c}}{${3}}', section: 'Graphics' },
  { label: '\\multirow', detail: 'Zeilenübergreifend', apply: '\\multirow{${1:2}}{*}{${2}}', section: 'Graphics' },

  // Mathematics
  { label: '\\frac', detail: 'Bruch', apply: '\\frac{${1}}{${2}}', section: 'Mathematics' },
  { label: '\\dfrac', detail: 'Bruch (groß)', apply: '\\dfrac{${1}}{${2}}', section: 'Mathematics' },
  { label: '\\tfrac', detail: 'Bruch (klein)', apply: '\\tfrac{${1}}{${2}}', section: 'Mathematics' },
  { label: '\\sqrt', detail: 'Wurzel', apply: '\\sqrt{${1}}', section: 'Mathematics' },
  { label: '\\sqrt[n]', detail: 'n-te Wurzel', apply: '\\sqrt[${1:n}]{${2}}', section: 'Mathematics' },
  { label: '\\sum', detail: 'Summe', apply: '\\sum_{${1:i=1}}^{${2:n}} ${0}', section: 'Mathematics' },
  { label: '\\prod', detail: 'Produkt', apply: '\\prod_{${1:i=1}}^{${2:n}} ${0}', section: 'Mathematics' },
  { label: '\\int', detail: 'Integral', apply: '\\int_{${1}}^{${2}} ${0}', section: 'Mathematics' },
  { label: '\\lim', detail: 'Limes', apply: '\\lim_{${1:n \\to \\infty}} ${0}', section: 'Mathematics' },
  { label: '\\limsup', detail: 'Limes superior', apply: '\\limsup_{${1:n \\to \\infty}} ${0}', section: 'Mathematics' },
  { label: '\\infty', detail: 'Unendlich', apply: '\\infty', section: 'Mathematics' },
  { label: '\\partial', detail: 'Partiell', apply: '\\partial', section: 'Mathematics' },
  { label: '\\nabla', detail: 'Nabla', apply: '\\nabla', section: 'Mathematics' },
  { label: '\\cdot', detail: 'Mittelpunkt', apply: '\\cdot', section: 'Mathematics' },
  { label: '\\times', detail: 'Malzeichen', apply: '\\times', section: 'Mathematics' },
  { label: '\\div', detail: 'Geteilt', apply: '\\div', section: 'Mathematics' },
  { label: '\\pm', detail: 'Plusminus', apply: '\\pm', section: 'Mathematics' },
  { label: '\\mp', detail: 'Minusplus', apply: '\\mp', section: 'Mathematics' },
  { label: '\\leq', detail: 'Kleiner-gleich', apply: '\\leq', section: 'Mathematics' },
  { label: '\\geq', detail: 'Larger-gleich', apply: '\\geq', section: 'Mathematics' },
  { label: '\\neq', detail: 'Ungleich', apply: '\\neq', section: 'Mathematics' },
  { label: '\\approx', detail: 'Ungefähr', apply: '\\approx', section: 'Mathematics' },
  { label: '\\equiv', detail: 'Äquivalent', apply: '\\equiv', section: 'Mathematics' },
  { label: '\\subset', detail: 'Teilmenge', apply: '\\subset', section: 'Mathematics' },
  { label: '\\subseteq', detail: 'Teilmenge-gleich', apply: '\\subseteq', section: 'Mathematics' },
  { label: '\\cup', detail: 'Vereinigung', apply: '\\cup', section: 'Mathematics' },
  { label: '\\cap', detail: 'Schnitt', apply: '\\cap', section: 'Mathematics' },
  { label: '\\in', detail: 'Element von', apply: '\\in', section: 'Mathematics' },
  { label: '\\notin', detail: 'Nicht Element', apply: '\\notin', section: 'Mathematics' },
  { label: '\\forall', detail: 'Für alle', apply: '\\forall', section: 'Mathematics' },
  { label: '\\exists', detail: 'Es existiert', apply: '\\exists', section: 'Mathematics' },
  { label: '\\emptyset', detail: 'Leere Menge', apply: '\\emptyset', section: 'Mathematics' },
  { label: '\\mathbb{R}', detail: 'Reelle Zahlen', apply: '\\mathbb{${1:R}}', section: 'Mathematics' },
  { label: '\\mathbf', detail: 'Bolder Vektor', apply: '\\mathbf{${1}}', section: 'Mathematics' },
  { label: '\\mathrm', detail: 'Aufrechte Schrift', apply: '\\mathrm{${1}}', section: 'Mathematics' },
  { label: '\\mathit', detail: 'Math. kursiv', apply: '\\mathit{${1}}', section: 'Mathematics' },
  { label: '\\operatorname', detail: 'Operatorname', apply: '\\operatorname{${1}}', section: 'Mathematics' },
  { label: '\\binom', detail: 'Binomialkoeffizient', apply: '\\binom{${1:n}}{${2:k}}', section: 'Mathematics' },
  { label: '\\overset', detail: 'Darüber', apply: '\\overset{${1}}{${2}}', section: 'Mathematics' },
  { label: '\\underset', detail: 'Darunter', apply: '\\underset{${1}}{${2}}', section: 'Mathematics' },
  { label: '\\dots', detail: 'Auslassungspunkte', apply: '\\dots', section: 'Mathematics' },
  { label: '\\vdots', detail: 'Vertikale Punkte', apply: '\\vdots', section: 'Mathematics' },
  { label: '\\ddots', detail: 'Diagonale Punkte', apply: '\\ddots', section: 'Mathematics' },

  { label: '\\newcommand', detail: 'Eigenen Befehl definieren', apply: '\\newcommand{\\${1:name}}[${2:1}]{${3:}}', section: 'Other' },
  { label: '\\newenvironment', detail: 'Eigene Umgebung', apply: '\\newenvironment{${1:name}}{${2:begin}}{${3:end}}', section: 'Other' },
  { label: '\\hfill', detail: 'Horizontaler Füllraum', apply: '\\hfill', section: 'Other' },
  { label: '\\vfill', detail: 'Vertikaler Füllraum', apply: '\\vfill', section: 'Other' },
  { label: '\\hspace', detail: 'Horizontaler Abstand', apply: '\\hspace{${1:1cm}}', section: 'Other' },
  { label: '\\vspace', detail: 'Vertikaler Abstand', apply: '\\vspace{${1:1cm}}', section: 'Other' },
  { label: '\\noindent', detail: 'Kein Einzug', apply: '\\noindent', section: 'Other' },
  { label: '\\setlength', detail: 'Länge setzen', apply: '\\setlength{\\${1:parindent}}{${2:0pt}}', section: 'Other' },
  { label: '\\linewidth', detail: 'Zeilenbreite', apply: '\\linewidth', section: 'Other' },
  { label: '\\textwidth', detail: 'Textbreite', apply: '\\textwidth', section: 'Other' },
  { label: '\\today', detail: 'Heutiges Datum', apply: '\\today', section: 'Other' },
];

/* ------------------------------------------------------- Umgebungen */

export const ENVIRONMENTS = [
  { label: 'equation', detail: 'Gleichung (nummeriert)', snippet: '\\begin{equation}\n\t$0\n\\end{equation}' },
  { label: 'equation*', detail: 'Gleichung (ohne Nr.)', snippet: '\\begin{equation*}\n\t$0\n\\end{equation*}' },
  { label: 'align', detail: 'Ausgerichtete Gleichungen', snippet: '\\begin{align}\n\t$0\n\\end{align}' },
  { label: 'align*', detail: 'Ausgerichtet (ohne Nr.)', snippet: '\\begin{align*}\n\t$0\n\\end{align*}' },
  { label: 'gather', detail: 'Grouped equations', snippet: '\\begin{gather}\n\t$0\n\\end{gather}' },
  { label: 'multline', detail: 'Multiline equation', snippet: '\\begin{multline}\n\t$0\n\\end{multline}' },
  { label: 'split', detail: 'Split equation', snippet: '\\begin{split}\n\t$0\n\\end{split}' },
  { label: 'cases', detail: 'Cases', snippet: '\\begin{cases}\n\t$0\n\\end{cases}' },
  { label: 'matrix', detail: 'Matrix', snippet: '\\begin{${1:p}matrix}\n\t$0\n\\end{$1matrix}' },
  { label: 'array', detail: 'Array matrix', snippet: '\\begin{array}{${1:cc}}\n\t$0\n\\end{array}' },
  { label: 'figure', detail: 'Abbildung', snippet: '\\begin{figure}[htbp]\n\t\\centering\n\t\\includegraphics[width=0.8\\linewidth]{${1:file}}\n\t\\caption{${2:Caption}}\n\t\\label{fig:${3:name}}\n\\end{figure}' },
  { label: 'figure*', detail: 'Full-width figure', snippet: '\\begin{figure*}[htbp]\n\t\\centering\n\t\\includegraphics[width=\\textwidth]{${1:file}}\n\t\\caption{${2:Caption}}\n\t\\label{fig:${3:name}}\n\\end{figure*}' },
  { label: 'table', detail: 'Tabelle', snippet: '\\begin{table}[htbp]\n\t\\centering\n\t\\caption{${1:Caption}}\n\t\\label{tab:${2:name}}\n\t\\begin{tabular}{${3:cc}}\n\t\t$0\n\t\\end{tabular}\n\\end{table}' },
  { label: 'tabular', detail: 'Spaltenlayout', snippet: '\\begin{tabular}{${1:cc}}\n\t$0\n\\end{tabular}' },
  { label: 'tabularx', detail: 'Breitenanpassende Tabelle', snippet: '\\begin{tabularx}{${1:\\linewidth}}{${2:X X}}\n\t$0\n\\end{tabularx}' },
  { label: 'longtable', detail: 'Mehrseitige Tabelle', snippet: '\\begin{longtable}{${1:cc}}\n\t$0\n\\end{longtable}' },
  { label: 'itemize', detail: 'Bulleted list', snippet: '\\begin{itemize}\n\t\\item ${1}\n\t$0\n\\end{itemize}' },
  { label: 'enumerate', detail: 'Numbered list', snippet: '\\begin{enumerate}\n\t\\item ${1}\n\t$0\n\\end{enumerate}' },
  { label: 'description', detail: 'Description list', snippet: '\\begin{description}\n\t\\item[${1:Term}] ${2}\n\t$0\n\\end{description}' },
  { label: 'center', detail: 'Centered', snippet: '\\begin{center}\n\t$0\n\\end{center}' },
  { label: 'quote', detail: 'Quote block', snippet: '\\begin{quote}\n\t$0\n\\end{quote}' },
  { label: 'quotation', detail: 'Quote block (eingerückt)', snippet: '\\begin{quotation}\n\t$0\n\\end{quotation}' },
  { label: 'verse', detail: 'Verse', snippet: '\\begin{verse}\n\t$0\n\\end{verse}' },
  { label: 'abstract', detail: 'Abstract', snippet: '\\begin{abstract}\n\t$0\n\\end{abstract}' },
  { label: 'theorem', detail: 'Theorem', snippet: '\\begin{theorem}[${1:Name}]\n\t$0\n\\end{theorem}' },
  { label: 'lemma', detail: 'Lemma', snippet: '\\begin{lemma}\n\t$0\n\\end{lemma}' },
  { label: 'proof', detail: 'Proof', snippet: '\\begin{proof}\n\t$0\n\\end{proof}' },
  { label: 'definition', detail: 'Definition', snippet: '\\begin{definition}\n\t$0\n\\end{definition}' },
  { label: 'corollary', detail: 'Corollary', snippet: '\\begin{corollary}\n\t$0\n\\end{corollary}' },
  { label: 'remark', detail: 'Remark', snippet: '\\begin{remark}\n\t$0\n\\end{remark}' },
  { label: 'example', detail: 'Example', snippet: '\\begin{example}\n\t$0\n\\end{example}' },
  { label: 'algorithm', detail: 'Algorithm', snippet: '\\begin{algorithm}\n\t\\caption{${1:Titel}}\n\t\\begin{algorithmic}[1]\n\t\t$0\n\t\\end{algorithmic}\n\\end{algorithm}' },
  { label: 'verbatim', detail: 'Wörtlich (kein Satz)', snippet: '\\begin{verbatim}\n\t$0\n\\end{verbatim}' },
  { label: 'lstlisting', detail: 'Quellcode (listings)', snippet: '\\begin{lstlisting}[language=${1:Python}]\n\t$0\n\\end{lstlisting}' },
  { label: 'frame', detail: 'Beamer frame', snippet: '\\begin{frame}{${1:Titel}}\n\t$0\n\\end{frame}' },
  { label: 'columns', detail: 'Beamer columns', snippet: '\\begin{columns}\n\t\\begin{column}{0.5\\linewidth}\n\t\t$0\n\t\\end{column}\n\\end{columns}' },
  { label: 'block', detail: 'Beamer block', snippet: '\\begin{block}{${1:Titel}}\n\t$0\n\\end{block}' },
  { label: 'titlepage', detail: 'Title page', snippet: '\\begin{titlepage}\n\t\\centering\n\t$0\n\\end{titlepage}' },
  { label: 'filecontents', detail: 'Write files', snippet: '\\begin{filecontents}{${1:file}}\n\t$0\n\\end{filecontents}' },
  { label: 'minipage', detail: 'Minipage', snippet: '\\begin{minipage}{${1:0.5\\linewidth}}\n\t$0\n\\end{minipage}' },
  { label: 'flushleft', detail: 'Left aligned', snippet: '\\begin{flushleft}\n\t$0\n\\end{flushleft}' },
  { label: 'flushright', detail: 'Right aligned', snippet: '\\begin{flushright}\n\t$0\n\\end{flushright}' },
];

/* ---------------------------------------------------------- Symbole */

export const SYMBOLS = [
  { cat: 'Greek', items: [
    ['α', '\\alpha'], ['β', '\\beta'], ['γ', '\\gamma'], ['δ', '\\delta'], ['ε', '\\varepsilon'],
    ['ζ', '\\zeta'], ['η', '\\eta'], ['θ', '\\theta'], ['ι', '\\iota'], ['κ', '\\kappa'],
    ['λ', '\\lambda'], ['μ', '\\mu'], ['ν', '\\nu'], ['ξ', '\\xi'], ['ο', 'o'],
    ['π', '\\pi'], ['ρ', '\\rho'], ['σ', '\\sigma'], ['τ', '\\tau'], ['υ', '\\upsilon'],
    ['φ', '\\varphi'], ['χ', '\\chi'], ['ψ', '\\psi'], ['ω', '\\omega'],
    ['Γ', '\\Gamma'], ['Δ', '\\Delta'], ['Θ', '\\Theta'], ['Λ', '\\Lambda'], ['Ξ', '\\Xi'],
    ['Π', '\\Pi'], ['Σ', '\\Sigma'], ['Φ', '\\Phi'], ['Ψ', '\\Psi'], ['Ω', '\\Omega'],
    ['∂', '\\partial'], ['∇', '\\nabla'], ['∀', '\\forall'], ['∃', '\\exists'], ['∅', '\\emptyset'],
  ] },
  { cat: 'Operatoren', items: [
    ['±', '\\pm'], ['∓', '\\mp'], ['×', '\\times'], ['÷', '\\div'], ['·', '\\cdot'],
    ['≤', '\\leq'], ['≥', '\\geq'], ['≠', '\\neq'], ['≈', '\\approx'], ['≡', '\\equiv'],
    ['∝', '\\propto'], ['∼', '\\sim'], ['≅', '\\cong'], ['≪', '\\ll'], ['≫', '\\gg'],
    ['∈', '\\in'], ['∉', '\\notin'], ['⊂', '\\subset'], ['⊆', '\\subseteq'], ['⊃', '\\supset'],
    ['∪', '\\cup'], ['∩', '\\cap'], ['⊕', '\\oplus'], ['⊗', '\\otimes'], ['⊙', '\\odot'],
    ['∑', '\\sum'], ['∏', '\\prod'], ['∫', '\\int'], ['∮', '\\oint'], ['√', '\\sqrt{}'],
    ['∞', '\\infty'], ['∖', '\\setminus'], ['∘', '\\circ'], ['∙', '\\bullet'],
    ['≪', '\\prec'], ['⟳', '\\circlearrowleft'], ['∴', '\\therefore'], ['∵', '\\because'],
  ] },
  { cat: 'Pfeile', items: [
    ['→', '\\to'], ['→', '\\rightarrow'], ['←', '\\leftarrow'], ['↔', '\\leftrightarrow'],
    ['⇒', '\\Rightarrow'], ['⇐', '\\Leftarrow'], ['⇔', '\\Leftrightarrow'], ['↦', '\\mapsto'],
    ['↑', '\\uparrow'], ['↓', '\\downarrow'], ['↗', '\\nearrow'], ['↘', '\\searrow'],
    ['⟹', '\\implies'], ['⟸', '\\impliedby'], ['⟺', '\\iff'], ['⇀', '\\rightharpoonup'],
    ['↝', '\\leadsto'], ['⟵', '\\longleftarrow'], ['⟶', '\\longrightarrow'],
  ] },
  { cat: 'Akzente', items: [
    ['á', "\\acute{a}"], ['à', "\\grave{a}"], ['ä', "\\ddot{a}"], ['ã', "\\tilde{a}"],
    ['ā', "\\bar{a}"], ['â', "\\hat{a}"], ['ă', "\\breve{a}"], ['č', "\\check{a}"],
    ['a̧', "\\c{a}"], ['å', "\\mathring{a}"], ['a̋', "\\H{a}"], ['á', "\\acute{}"],
    ['x̂', "\\hat{}"], ['x̃', "\\tilde{}"], ['x̄', "\\bar{}"], ['ẋ', "\\dot{}"],
    ['ẍ', "\\ddot{}"], ['x̌', "\\check{}"], ['x̣', "\\underbrace{}"],
  ] },
  { cat: 'Klammern', items: [
    ['(', '('], [')', ')'], ['[', '['], [']', ']'], ['{', '\\{'], ['}', '\\}'],
    ['⟨', '\\langle'], ['⟩', '\\rangle'], ['⌈', '\\lceil'], ['⌉', '\\rceil'],
    ['⌊', '\\lfloor'], ['⌋', '\\rfloor'], ['|', '|'], ['‖', '\\|'],
    ['(', '\\left('], [')', '\\right)'], ['[', '\\left['], [']', '\\right]'],
    ['{', '\\left\\{'], ['}', '\\right\\}'], ['⌊', '\\left\\lfloor'], ['↑', '\\left\\uparrow'],
  ] },
  { cat: 'Pfeile-Symbole', items: [
    ['⊕', '\\oplus'], ['⊖', '\\ominus'], ['⟨', '\\langle'], ['ℤ', '\\mathbb{Z}'],
    ['ℕ', '\\mathbb{N}'], ['ℚ', '\\mathbb{Q}'], ['ℝ', '\\mathbb{R}'], ['ℂ', '\\mathbb{C}'],
    ['ℙ', '\\mathbb{P}'], ['𝔼', '\\mathbb{E}'], ['.Var', '\\operatorname{Var}'],
    ['arg', '\\operatorname{arg}'], ['max', '\\max'], ['min', '\\min'], ['sup', '\\sup'],
    ['inf', '\\inf'], ['lim', '\\lim'], ['log', '\\log'], ['ln', '\\ln'], ['exp', '\\exp'],
    ['sin', '\\sin'], ['cos', '\\cos'], ['tan', '\\tan'], ['arctan', '\\arctan'],
    ['det', '\\det'], ['dim', '\\dim'], ['ker', '\\ker'], ['deg', '\\deg'],
  ] },
  { cat: 'Text', items: [
    ['ß', '\\ss'], ['“', '“'], ['“', '“'], ['–', '--'], ['—', '---'],
    ['…', '\\ldots'], ['†', '\\dagger'], ['‡', '\\ddagger'], ['§', '\\S'],
    ['¶', '\\P'], ['©', '\\copyright'], ['®', '\\textregistered'], ['™', '\\texttrademark'],
    ['€', '\\texteuro'], ['°', '\\textdegree'], ['±', '\\pm'], ['×', '\\times'],
    ['nbsp', '~'], ['ligatur', '\\--'], ['footnote', '\\footnote{}'],
  ] },
  { cat: 'Structure', items: [
    ['§', '\\section{}'], ['¶', '\\subsection{}'], ['•', '\\item'],
    ['1.', '\\begin{enumerate}\n\t\\item \n\\end{enumerate}'], ['•', '\\begin{itemize}\n\t\\item \n\\end{itemize}'],
    ['Eq', '\\begin{equation}\n\t\n\\end{equation}'], ['Eq*', '\\begin{equation*}\n\t\n\\end{equation*}'],
    ['Fig', '\\begin{figure}[htbp]\n\t\\centering\n\t\\includegraphics[width=0.8\\linewidth]{}\n\t\\caption{}\n\t\\label{fig:}\n\\end{figure}'],
    ['Tab', '\\begin{table}[htbp]\n\t\\centering\n\t\\caption{}\n\t\\label{tab:}\n\t\\begin{tabular}{cc}\n\t\t\n\t\\end{tabular}\n\\end{table}'],
    ['Bf', '\\textbf{}'], ['It', '\\textit{}'], ['Fr', '\\frac{}{}'], ['Sq', '\\sqrt{}'],
    ['Href', '\\href{}{}'], ['Cite', '\\cite{}'], ['Ref', '\\ref{}'], ['Lbl', '\\label{}'],
  ] },
];

/* --------------------------------------------------- Dokumentvorlagen */

export const DOC_SNIPPETS = [
  { label: 'Document skeleton', detail: 'Starter structure with packages', snippet:
    '\\documentclass[${1:12pt}]{${2:article}}\n\n\\usepackage[${3:ngerman}]{babel}\n\\usepackage{amsmath}\n\\usepackage{graphicx}\n\\usepackage{hyperref}\n\n\\title{${4:Titel}}\n\\author{${5:Autor}}\n\\date{\\today}\n\n\\begin{document}\n\\maketitle\n\n$0\n\n\\end{document}' },
  { label: 'Section', detail: 'section + label', snippet: '\\section{${1:Titel}}\\label{sec:${2:name}}\n$0' },
  { label: 'Abbildung', detail: 'figure-Umgebung', snippet: '\\begin{figure}[htbp]\n\t\\centering\n\t\\includegraphics[width=0.8\\linewidth]{${1:file}}\n\t\\caption{${2:Caption}}\n\t\\label{fig:${3:name}}\n\\end{figure}' },
  { label: 'Tabelle', detail: 'table + booktabs', snippet: '\\begin{table}[htbp]\n\t\\centering\n\t\\caption{${1:Caption}}\n\t\\label{tab:${2:name}}\n\t\\begin{tabular}{${3:lrr}}\n\t\t\\toprule\n\t\t${4:Spalte} & {Wert} & {Wert} \\\\\n\t\t\\midrule\n\t\t$0\n\t\t\\bottomrule\n\t\\end{tabular}\n\\end{table}' },
  { label: 'Gleichung', detail: 'equation mit Label', snippet: '\\begin{equation}\n\t${1:A = B}$\n\t\\label{eq:${2:name}}\n\\end{equation}' },
  { label: 'itemize', detail: 'Stichpunkte', snippet: '\\begin{itemize}\n\t\\item ${1}\n\t$0\n\\end{itemize}' },
  { label: 'Zitat', detail: 'cite + Verweis', snippet: '${1:Aussage}~\\cite{${2:key}}.' },
];
